# config/packages/easy_admin.yaml

easy_admin:
    design:
        templates:
            layout: '@EasyAdmin/default/layout.html.twig'
    entities:
        Etudiant:
            class: App\Entity\Etudiant
            label: 'Étudiants'
